s2m/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from app import views

urlpatterns = (
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.MainPage.as_view()),
    path('scientists/', views.ScientistsPage.as_view(), name="scientists"),
    path('scientists/search', views.Search.as_view(), name="search"),
    path('profile/<str:profile_id>', views.ProfilePage.as_view(), name="profile"),
    path('information/', views.information, name="information"),
    path('report/', login_required(views.report), name="report"),
    path('report/export_xlsx/', login_required(views.export_xlsx), name="export_xlsx"),
    path('report/export5_xlsx/', login_required(views.export5_xlsx), name="export5_xlsx"),
    path('report/naukometria_xlsx/', login_required(views.naukometria_xlsx), name="naukometria_xlsx"),
    path('scientists/update_scientists_records', login_required(views.update_scientists_records), name="update_scientists_records"),
)

app/models.py
from django.db import models
from django.urls.base import reverse


class Institute(models.Model):
    id_institute = models.AutoField(primary_key=True)
    title_institute = models.CharField('Назва', unique=True, max_length=300)
    abbreviation = models.CharField('Абревіатура', unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'institute'
        verbose_name = 'Інститут'
        verbose_name_plural = 'Інститути'

    def __str__(self):
        return self.title_institute


class Faculty(models.Model):
    id_faculty = models.AutoField(primary_key=True)
    title_faculty = models.CharField('Назва', unique=True, max_length=300)
    institute = models.ForeignKey('Institute', on_delete=models.CASCADE, db_column='institute', to_field='id_institute',
                                  verbose_name="Інститут")
    abbreviation = models.CharField('Абревіатура', unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'faculty'
        verbose_name = 'Факультет'
        verbose_name_plural = 'Факультети'

    def __str__(self):
        return self.title_faculty


class Department(models.Model):
    id_department = models.AutoField(primary_key=True)
    title_department = models.CharField('Назва', unique=True, max_length=300)
    abbreviation = models.CharField('Абревіатура', unique=True, max_length=50, blank=True, null=True)
    faculty = models.ForeignKey('Faculty', on_delete=models.CASCADE, db_column='faculty', to_field='id_faculty',
                                verbose_name="Факультет")

    class Meta:
        managed = False
        ordering = ('title_department',)
        db_table = 'department'
        verbose_name = 'Кафедра'
        verbose_name_plural = 'Кафедри'

    def __str__(self):
        return self.title_department


class Degree(models.Model):
    id_degree = models.AutoField(primary_key=True)
    title_degree = models.CharField('Назва', unique=True, max_length=200)

    class Meta:
        managed = False
        ordering = ('title_degree',)
        db_table = 'degree'
        verbose_name = 'Наукова ступінь'
        verbose_name_plural = 'Наукові ступені'

    def __str__(self):
        return self.title_degree


class Post(models.Model):
    id_post = models.AutoField(primary_key=True)
    title_post = models.CharField('Назва', unique=True, max_length=300)

    class Meta:
        managed = False
        db_table = 'post'
        verbose_name = 'Посада'
        verbose_name_plural = 'Посади'

    def __str__(self):
        return self.title_post


class Rank(models.Model):
    id_rank = models.AutoField(primary_key=True)
    title_rank = models.CharField('Назва', unique=True, max_length=200)

    class Meta:
        managed = False
        db_table = 'rank'
        verbose_name = 'Наукове звання'
        verbose_name_plural = 'Наукові звання'

    def __str__(self):
        return '%s' % self.title_rank


class Scientist(models.Model):
    id_scientist = models.AutoField(primary_key=True)
    lastname_uk = models.CharField('Прізвище', max_length=200)
    firstname_uk = models.CharField('Ім\'я', max_length=100)
    middlename_uk = models.CharField('Ім\'я по-батькові', max_length=100)
    lastname_en = models.CharField('Прізвище (англ.)', max_length=200)
    firstname_en = models.CharField('Ім\'я (англ.)', max_length=100)
    email = models.EmailField('E-mail', max_length=300, blank=True)
    department = models.ForeignKey('Department', on_delete=models.CASCADE, db_column='department',
                                   to_field='id_department', verbose_name="Кафедра")
    rank = models.ForeignKey('Rank', on_delete=models.CASCADE, db_column='rank', to_field='id_rank', blank=True,
                             verbose_name="Наукове звання")
    degree = models.ForeignKey('Degree', on_delete=models.CASCADE, db_column='degree', to_field='id_degree', blank=True, null=True,
                               verbose_name="Наукова ступінь")
    post = models.ForeignKey('Post', on_delete=models.CASCADE, db_column='post', to_field='id_post', blank=True, null=True,
                             verbose_name="Посада")
    speciality = models.ManyToManyField('Speciality', blank=True, verbose_name="Спеціальність")
    work_state = models.ForeignKey('WorkState', on_delete=models.CASCADE, db_column='work_state', to_field='id_state',
                                   verbose_name="Робочий статус", default="Працює")
    orcid = models.CharField('ORCID', max_length=25, help_text="0000-0002-1398-1472", blank=True)
    google_scholar = models.CharField('Google Scholar', max_length=200, blank=True, null=False, unique=False,
                                      help_text="У GS ID можуть бути знаки \"-\", \"_\" на початку, або всередені (приклад -\"_EF1_85cAAAAJ\"), копіюємо код у в адресному рядку після \'?user=\'")
    h_index_google_scholar = models.PositiveSmallIntegerField('h-індекс Google Scholar', blank=True, default=0)
    google_scholar_count_pub = models.PositiveSmallIntegerField('Кількість публікацій Google Scholar', blank=True, default=0)
    publons = models.CharField('Web of Science', max_length=100, blank=True, null=False, unique=False, help_text="Приклад: 799072, останні цифри після слешу \'/\' у адресному рядку профіля")
    h_index_publons = models.PositiveSmallIntegerField('h-індекс WoS', default=0)
    publons_count_pub = models.PositiveSmallIntegerField('Кількість публікацій WoS', default=0)
    scopusid = models.CharField('Scopus ID', max_length=200, blank=True, null=False, unique=False,
                                help_text="Приклад: 24337331300, останні цифри після \'?authorId=\' у адресному рядку профіля")
    h_index_scopus = models.PositiveSmallIntegerField('h-індекс Scopus', blank=True, default=0)
    scopus_count_pub = models.PositiveSmallIntegerField('Кількість публікацій Scopus', blank=True, default=0)
    publication_wos = models.ManyToManyField('PublicationWos', blank=True, verbose_name="Публікації WoS")
    publication_scopus = models.ManyToManyField('PublicationScopus', blank=True, verbose_name="Публікації Scopus")
    date_update = models.DateField("Дата оновленя", auto_now=True, null=False)
    profile_id = models.CharField('Код користувача', max_length=4, editable=True, unique=True, blank=True)
    draft = models.BooleanField('Чернетка', default=False)
    staff = models.BooleanField('У штаті', default=False)
    
    class Meta:
        managed = False
        db_table = 'scientist'
        verbose_name = 'Науковець'
        verbose_name_plural = 'Науковці'
        

    def save(self, *args, **kwargs):
        super(Scientist, self).save()
        if not self.profile_id:
            self.profile_id = str(self.id_scientist)
            self.profile_id = self.profile_id.zfill(4)
            super(Scientist, self).save()

    def get_absolute_url(self):
        return reverse("profile", kwargs={"profile_id": self.profile_id})
    

    def __str__(self):
        return '%s %s %s' % (self.lastname_uk, self.firstname_uk, self.middlename_uk)


class PublicationScopus(models.Model):
    id_publication = models.AutoField(primary_key=True, db_column='id_publication')
    publication_title = models.CharField('Публікація Scopus', unique=True, max_length=1000)
    doi = models.CharField('DOI Публікації Scopus', blank=True, max_length=200)
    link = models.CharField('Посилання на публікацію Scopus', blank=True, max_length=500)

    class Meta:
        managed = False
        db_table = 'publication_scopus'
        verbose_name = 'Публікація Scopus'
        verbose_name_plural = 'Публікації Scopus'

    def __str__(self):
        return '%s' % self.publication_title


class ScientistPublicationScopus(models.Model):
    publicationscopus_id = models.AutoField(primary_key=True, null=False, db_column='publicationscopus_id')
    scientist_id = models.ForeignKey(Scientist, db_column='scientist_id', on_delete=models.CASCADE, null=True,
                                     to_field='id_scientist', verbose_name="Науковець")
    publication_id = models.ForeignKey(PublicationScopus, db_column='publication_id', on_delete=models.CASCADE, null=True,
                                      to_field='id_publication', verbose_name="Публікація Scopus")

    class Meta:
        managed = False
        db_table = 'scientist_publication_scopus'
        verbose_name = 'Науковець - Публікація Scopus'
        verbose_name_plural = 'Науковці - Публікації Scopus'


class PublicationWos(models.Model):
    id_publication = models.AutoField(primary_key=True, db_column='id_publication')
    publication_title = models.CharField('Публікації WoS', unique=True, max_length=1000)
    doi = models.CharField('DOI Публікації WoS', blank=True, null=True, max_length=200)
    link = models.CharField('Посилання на публікацію Scopus', blank=True, null=True, max_length=500)

    class Meta:
        managed = False
        db_table = 'publication_wos'
        verbose_name = 'Публікація WoS'
        verbose_name_plural = 'Публікації WoS'

    def __str__(self):
        return '%s' % self.publication_title


class ScientistPublicationWos(models.Model):
    publicationwos_id = models.AutoField(primary_key=True, null=False)
    scientist_id = models.ForeignKey(Scientist, db_column='scientist_id', on_delete=models.CASCADE, null=True,
                                     to_field='id_scientist', verbose_name="Науковець")
    publication_id = models.ForeignKey(PublicationWos, db_column='publication_id', on_delete=models.CASCADE, null=True,
                                      to_field='id_publication', verbose_name="Публікація Wos")

    class Meta:
        managed = False
        db_table = 'scientist_publication_wos'
        verbose_name = 'Науковець - Публікація WoS'
        verbose_name_plural = 'Науковці - Публікації WoS'


class Speciality(models.Model):
    id_speciality = models.AutoField(primary_key=True)

templates/base.html
<!DOCTYPE html>
<html lang="uk">

{%load static%}

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="s2m, Наукометрія, ОНТУ, ONTU, ONUT, вчений, вчені, Scientific, Science to Metrics, ключеве слово, науковець, нацковці, Scopus, Web of Science, WoS, Google Scholar, GS, h-index, індекс Хірша, ОНАХТ, ОНАПТ, ONAFT, ONTU, ОНТУ, ONTULibrary, Звіти, ORCID, Publons, Посада, Ступінь, Звання, Спеціальність, Інститут, Факультет, Кафедра, публікація, публікації, кількість публікацій, Рейтинг, Топ, Звіт, Звіти, Профіль" />
    <meta name="description" content="Платформа, яка зберігає список всії наукових робіт і буде пов'язана з усіма сучасними сервісами надають розрахунок наукометричних показників." />
    <meta name="viewport" content="width=device-width" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@200;300;400&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'assets/icons/favicon.ico' %}" type="image/x-icon">
    <!-- Style - CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <!-- /Style - CSS -->
    <!-- ChartJS -->
    <script type="text/javascript" src="{% static 'javascript/Chart.min.js' %}"></script>
    <!-- /ChartJS -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-315STGK4G8"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-315STGK4G8');
    </script>
</head>

<body>
    <div class="page_wrap">
    {% include "includes/header.html" %}
    <section class="content">
        <div class="wrapper">
            <div class="block_content">
                <div class="headline_content">
                    <h3 class="headline_content_title">{% block headtitle %}{% endblock %}</h3>
                </div>
                {% block content %} {% endblock %}
            </div>
        </div>
    </section>
    </div>
    {% include "includes/footer.html" %}

    <!-- Javascript -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="{% static 'javascript/main.js' %}"></script>
    <!-- /Javascript -->

</body>

</html>

templates/profilePage.html
{% extends "base.html" %}{% block title %} Профіль {% endblock %} {% block headtitle %} Профіль {% endblock %} {% block content %}


<div class="profile_header">
    <h4 class="profile_header_title">
        <p class="profile_header_name">{{scientist.lastname_uk}} {{scientist.firstname_uk}} {{scientist.middlename_uk}}</p>
        <p class="profile_header_name_en">{{scientist.lastname_en}} {{scientist.firstname_en}}</p>
        <div class="profile_header_code">
            <p class="profile_header_code_title">Код вченого:</p>
            <p class="profile_header_code_id">{{scientist.profile_id}}</p>
        </div>
    </h4>
    
    <div class="profile_date_update">
        <p class="profile_date_update_title">Оновлено:</p>
        <div class="profile_date_update_data">
            {{scientist.date_update}}
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'profile' profile_id=scientist.profile_id %}">
                {% csrf_token %}
                <input type="submit" value="Оновити" class="profile_update_button">
            </form>
            {% endif %}
        </div>
        
    </div>
</div>

<hr class="dividing_line ">
<div class="profile_main_info">
    <ul class="profile_main_info_list">
        <li class="profile_info_item">
            <p class="profile_info_item_title">Інститут:</p>
            <p class="profile_info_item_data">{{scientist.department.faculty.institute.title_institute}}</p>
        </li>
        <!-- <li class="profile_info_item">
            <p class="profile_info_item_title">Факультет:</p>
            <p class="profile_info_item_data">{{scientist.department.faculty.title_faculty}}</p>
        </li> -->
        <li class="profile_info_item">
            <p class="profile_info_item_title">Кафедра:</p>
            <p class="profile_info_item_data"><a href="{% url 'search' %}?&select=department&q={{scientist.department|urlencode}}&filter=fullname_up">{{scientist.department}}</a></p>
        </li>
        <li class="profile_info_item">
            <p class="profile_info_item_title">Посада:</p>
            <p class="profile_info_item_data">
                {% if scientist.post == "" %} Немає {% else %} {{scientist.post}} {% endif %}
            </p>
        </li>
        <li class="profile_info_item">
            <p class="profile_info_item_title">Ступінь:</p>
            <p class="profile_info_item_data">
                {% if scientist.degree == None %} Немає {% else %} {{scientist.degree}} {% endif %}
            </p>
        </li>
        <li class="profile_info_item">
            <p class="profile_info_item_title">Звання:</p>
            <p class="profile_info_item_data">
                {% if scientist.rank == "" %} Немає {% else %} {{scientist.rank}} {% endif %}
            </p>
        </li>
        <li class="profile_info_item">
            <p class="profile_info_item_title">Спеціальність:</p>
            <p class="profile_info_item_data">
                {% if scientist.speciality.all %}
                    {% for speciality in scientist.speciality.all %}
                        <a href="{% url 'search' %}?&select=speciality&q={{speciality.speciality_title|urlencode}}&filter=fullname_up">{{speciality.speciality_code}} {{speciality.speciality_title}}</a>;
                    {% endfor %}
                {% else %}
                    Немає
                {% endif %}
            </p>
        </li>
        <li class="profile_info_item">
            <p class="profile_info_item_title">Ключові слова:</p>
            <p class="profile_info_item_data">
                {% if scientist.speciality.all %}
                    {% for speciality in scientist.speciality.all %}
                        {% for keyword in speciality.keyword.all %}
                            <a href="{% url 'search' %}?&select=keyword&q={{keyword.keyword_title}}&filter=fullname_up ">{{keyword.keyword_title}}</a>;
                        {% endfor %}
                    {% endfor %}
                {% else %}
                    Немає
                {% endif %}
            </p>
        </li>
        <!--         
        <li class="profile_info_item">
            <p class="profile_info_item_title">E-mail:</p><a href="mailto:{{scientist.email}}" class="profile_info_item_data profile_scientific_info_link">{{scientist.email}}</a>
        </li> -->
<!--        <li class="profile_info_item">-->
<!--            <p class="profile_info_item_title">Стан:</p>-->
<!--            <p class="profile_info_item_data">{{scientist.work_state}}</p>-->
<!--        </li>-->
    </ul>
</div>
<hr class="dividing_line ">
<div class="profile_scientific_info_block">
    <div class="profile_info_item">
        <p class="profile_info_item_title">ORCID:</p>
        <a href="https://orcid.org/{{scientist.orcid}}" target="_blank" class="profile_info_item_data profile_scientific_info_link">{{scientist.orcid}}</a>
    </div>
    <div class="profile_scientific_info_indicators">
        <ul class="profile_scientific_info_indicators_list">
            <li class="profile_info_item">
                <p class="profile_info_item_title">Google Scholar:</p>
                {% if scientist.google_scholar == '' %} Немає {% else %}
                <a href="https://scholar.google.com/citations?user={{scientist.google_scholar}}" target="_blank" class="profile_info_item_data profile_scientific_info_link">Посилання</a> {% endif %}
            </li>
            <li class="profile_info_item">
                <p class="profile_info_item_title">h index Google Scholar:</p>
                <p class="profile_info_item_data">{{scientist.h_index_google_scholar}}</p>
            </li>
            <li class="profile_info_item">
                <p class="profile_info_item_title">Кількість публікацій:</p>
                <p class="profile_info_item_data">{{scientist.google_scholar_count_pub}}</p>
            </li>
        </ul>
        <ul class="profile_scientific_info_indicators_list">
            <li class="profile_info_item">
                <p class="profile_info_item_title">Publons:</p>
                {% if scientist.publons == '' %} Немає {% else %}
                <a href="https://www.webofscience.com/wos/author/record/{{scientist.publons}}" target="_blank" class="profile_info_item_data profile_scientific_info_link">{{scientist.publons}}</a> {% endif %}
            </li>
            <li class="profile_info_item">
                <p class="profile_info_item_title">h index Web of Science:</p>
                <p class="profile_info_item_data">{{scientist.h_index_publons}}</p>
            </li>
            <li class="profile_info_item">
                <p class="profile_info_item_title">Кількість публікацій:</p>
                <p class="profile_info_item_data">{{scientist.publons_count_pub}}</p>
            </li>
        </ul>
        <ul class="profile_scientific_info_indicators_list">
            <li class="profile_info_item">
                <p class="profile_info_item_title">Scopus ID:</p>
                {% if scientist.scopusid == '' %} Немає {% else %}
                <a href="https://www.scopus.com/authid/detail.uri?authorId={{scientist.scopusid}}" target="_blank" class="profile_info_item_data profile_scientific_info_link">{{scientist.scopusid}}</a> {% endif %}
            </li>
            <li class="profile_info_item">
                <p class="profile_info_item_title">h index Scopus:</p>
                <p class="profile_info_item_data">{{scientist.h_index_scopus}}</p>
            </li>
            <li class="profile_info_item">
                <p class="profile_info_item_title">Кількість публікацій:</p>
                <p class="profile_info_item_data">{{scientist.scopus_count_pub}}</p>
            </li>
        </ul>
    </div>

    <div class="profile_scientific_info_chart">
        <div class="profile_scientific_info_chart_block">
            <div class="profile_scientific_info_chart_title">Рейтинг h index</div>
            <div class="profile_scientific_info_chart_area">
                <canvas class="rating_chart" id="h_index"></canvas>
                <script type="text/javascript">
                    var a = document.getElementById('h_index').getContext('2d');
                    var label = ['Web of Science', 'Scopus', 'Google Scholar']
                    var data = ['{{scientist.h_index_publons}}', '{{scientist.h_index_scopus}}', '{{scientist.h_index_google_scholar}}']
                    var myLineChart = new Chart(a, {
                        type: 'bar',
                        data: {
                            labels: label,
                            datasets: [{
                                data: data,
                                backgroundColor: [
                                    'rgba(54, 162, 235, 0.6)',
                                    'rgba(75, 192, 192, 0.6)',
                                    'rgba(255, 206, 86, 0.6)',

                                ],
                            }]
                        },
                        options: {
                            legend: {
                                display: false
                            },
                            scales: {
                                xAxes: [{
                                    display: true
                                }],
                                yAxes: [{
                                    display: true,
                                    ticks: {
                                        beginAtZero: true,
                                        stepSize: 1
                                    }
                                }]
                            }

                        }
                    });
                </script>
            </div>
        </div>
        <div class="profile_scientific_info_chart_block">
            <div class="profile_scientific_info_chart_title">Рейтинг кількості публікацій</div>
            <div class="profile_scientific_info_chart_area">
                <canvas class="rating_chart" id="count_pub"></canvas>
                <script type="text/javascript">
                    //    'Google Scholar',
                    //    '{{scientist.google_scholar_count_pub}}',
                    var a = document.getElementById('count_pub').getContext('2d');
                    var label = ['Web of Science', 'Scopus']
                    var data = ['{{scientist.publons_count_pub}}', '{{scientist.scopus_count_pub}}']
                    var myLineChart = new Chart(a, {
                        type: 'bar',
                        data: {
                            labels: label,
                            datasets: [{
                                data: data,
                                backgroundColor: [
                                    'rgba(75, 192, 192, 0.6)',
                                    'rgba(255, 206, 86, 0.6)',
                                ],
                            }]
                        },
                        options: {
                            legend: {
                                display: false
                            },
                            scales: {
                                xAxes: [{
                                    display: true
                                }],
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: true,
                                        stepSize: 20
                                    }
                                }]
                            }

                        }
                    });
                </script>
            </div>
        </div>
    </div>
</div>
{% if scientist.publicationwos_set.all or scientist.publicationscopus_set.all %}
<div class="profile_publication_info">
    <h5 class="profile_publication_info_title">Публікації</h5>
    {% if scientist.publicationwos_set.all %}
    <div class="profile_publication_info_block">
        <h6 class="profile_publication_info_block_title">Web of Science</h6>
        <p class="profile_publication_info_data">
            {% for pubs_wos in scientist.publicationwos_set.all %}
                <p class="profile_publication_info_item">
                    {{forloop.counter}}. {{pubs_wos.publication_title}}
                </p>
            {% endfor %}
        </p>
    </div>
    {% else %}
    {% endif %}
{% if scientist.publicationscopus_set.all %}
    <div class="profile_publication_info_block">
        <h6 class="profile_publication_info_block_title">Scopus</h6>
        <p class="profile_publication_info_data">
            {% for pubs_scopus in scientist.publicationscopus_set.all %}
                <p class="profile_publication_info_item">
                    {{forloop.counter}}. {{pubs_scopus.publication_title}}
                </p>
            {% endfor %}
        </p>
    </div>
    {% else %}
    {% endif %}
</div>
{% else %}
{% endif %}
{% endblock %}

templates/reportPage.html
{% extends "base.html" %}{% block title %} Звіти {% endblock %} {% block headtitle %} Звіти {% endblock %} {% block content %}
    {% load static%}
<div class="report_block">
    <div class="report_information_block">
        <div class="report_information">
            <p class="report_information_paragraph">Табліця 3 та Табліця 4. Річний звіт про виконання критеріїв.<br> Включає такі дані: </p>
            <li class="report_information_list_item">
                Факультет (Інститут);
            </li>
            <li class="report_information_list_item">
                Кафедра, відділ тощо;
            </li>
            <li class="report_information_list_item">
                Прізвище, ім'я, по батькові наукового, науково-педагогічного працівника.
            </li>
            <li class="report_information_list_item">
                ID Scopus (за наявності).
            </li>
            <li class="report_information_list_item">
                Індекс Гірша Scopus.
            </li>
            <li class="report_information_list_item">
                Кількість публікацій Scopus.
            </li>
            <li class="report_information_list_item">
                ID Web of Science.
            </li>
            <li class="report_information_list_item">
                Індекс Гірша Web of Science.
            </li>
            <li class="report_information_list_item">
                Кількість публікацій WoS.
            </li>
            <li class="report_information_list_item">
                Публікації Web of Science.
            </li>
            <li class="report_information_list_item">
                Публікації Scopus.
            </li>
        </div>
        <div class="main_button_block">
            <a href="{% url 'export_xlsx' %}" class="report_export_link">
                <button class="main_button">
                    Експорт
                </button>
            </a>
            <a href="{% url 'export5_xlsx' %}" class="report_export_link">
                <button class="main_button">
                    Експорт за кількістю пуб-й
                </button>
            </a>
            <a href="{% url 'naukometria_xlsx' %}" class="report_export_link">
                <button class="main_button">
                    Наукометрія
                </button>
            </a>
        </div>
    </div>
    <div class="report_example">
        <div class="report_document_background">
            <img class="report_document_example" src="{% static 'assets/Document_table_3.jpg' %}">
        </div>
    </div>
</div>
<!-- 
<a href="/export">Експорт</a>
<a href="/export_xls">Експорт xls</a> -->
{% endblock %}